# shellcheck shell=bash
# Snow (testnet) node IDs
SNOW_NODE_IDS='["NodeID-7TwAjiRpTbNcqUx6F9EoyXRBLAfeoQXRq","NodeID-JbeonHKqomERomXgCiXr9oC9vfynkBupj","NodeID-BffXkmzM8EwrBZgpqFp9pwgE9DbDgYKG2","NodeID-24WK7qiKXAumya1kKEktwj2ubBbRyq5UW","NodeID-A2Z8m7egVLhKf1Qj14uvXadhExM5zrB7p"]'

# Jade (mainnet) node IDs
JADE_NODE_IDS='["NodeID-BXTBUqX8gitUDtVam4fhRWGD1SfeHGoBx"]'
