name: Add Issues to Backlog Project

on:
  issues:
    types:
      - opened

permissions:
  issues: read

concurrency:
  group: add-to-project-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  add-to-project:
    name: Add issue to Backlog project
    runs-on: ubuntu-24.04
    steps:
      - name: Add issue to Backlog project
        uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c # v1.0.2
        with:
          project-url: https://github.com/orgs/numbersprotocol/projects/8
          # OR for repository projects:
          # project-url: https://github.com/users/YOUR_USERNAME/projects/YOUR_PROJECT_NUMBER
          # OR for user projects:
          # project-url: https://github.com/users/YOUR_USERNAME/projects/YOUR_PROJECT_NUMBER
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
